---
title: |
  | Synergistic Activities
date: "Frederick Solt"
output: 
  pdf_document
documentclass: nsf2
header-includes:
      - \setlength{\parindent}{0cm}
      - \geometry{margin=1in}
      - \usepackage{times}
      - \usepackage[fontsize=12pt]{scrextend}
      - \usepackage{wrapfig}
---

1. Coauthor, publisher, and maintainer of R packages (DCPO, DCPOtools) that facilitating the collection and manipulation of cross-national survey data and the estimation of Bayesian latent variable estimates of public opinion.
These packages exceed 200 downloads/month.
1. Coauthor, publisher, and maintainer of R packages (ropercenter, icpsrdata, pewdata, gesisdata) facilitating reproducible data retrieval from various data archives.
These packages exceed 900 downloads/month.
1. Coauthor of articles using surveys from around the world to generate comparable estimates of (a) public opinion toward gender roles and (b) political interest.  Maintainer of DCPO website at https://dcpo.org/ to transfer knowledge on these topics to an international audience of scholars, policymakers, journalists, students, and the public.
Traffic to site exceeds 25 pageloads/day.
1. Author of Standardized World Income Inequality Database and maintainer of SWIID website at https://fsolt.org/swiid/ to transfer knowledge about income inequality around the world to a broad and international audience of scholars, policymakers, journalists, students, and the public. 
Traffic to site exceeds 100 pageloads/day.
1. Coauthor, publisher, and maintainer of R packages (dotwhisker, interplot) facilitating visualization of the results of statistical analyses.  These packages exceed 13,000 downloads/month.