---
title: "Project Summary"
date: "\\vspace{-3em}"
header-includes:
  - \setlength{\parindent}{0cm}
  - \geometry{margin=1in}
output: 
  pdf_document:
   includes:
    in_header: style/preamble.tex
   template: null
   keep_tex: no
   number_sections: false
  word_document:
   toc: false
   number_sections: false
documentclass: style/nsf2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

Addressing climate change effectively requires understanding the interplay between policy, politics, and public opinion.
Understanding how public opinion on climate change affects policy, especially across partisan lines, urban-rural divides, and gender differences, is crucial as polarization challenges the implementation and sustainability of climate reforms.
However, research in this area has been impeded by the absence of comparable, longitudinal, and cross-national public opinion data.
The Climate Change Public Opinion Database (CCPOD) aims to overcome these challenges by using the Dynamic Comparative Public Opinion model, a Bayesian Item Response Theory Model, on data drawn from national, regional, and worldwide survey projects, as well as academic studies to generate a time-series cross-national estimates dataset.
The CCPOD has currently collected 93 different survey projects from 1992 to 2022, providing a cornerstone for further data expansion and latent variable measures.
The proposed research comprises five principal activities to build the CCPOD project: (1) acquiring and cleaning data to expand its coverage, (2) assessing and improving the multiple-imputation routine by incorporating new techniques to ensure its estimates are comparable, (3) setting stronger priors for change over time and in data-poor countries, and nesting similar items in hierarchical models to address item-comparability issues, (4) developing and testing various methods for generating polarization estimates, and (5) developing a web-based system for disseminating the CCPOD to researchers, educators, and policymakers worldwide.

## Intellectual Merit

Scholars in political science, economics, public policy, environmental engineering, ecosystem science, and other social and natural sciences have long sought to address climate change due to its lasting effects on economic development, human rights, social justice and equality, voting behaviors, and political violence.
Understanding public opinion is crucial because it directly influences the feasibility and sustainability of policy interventions.
Policies that align with public attitudes are more likely to gain the necessary support for implementation and endure over time.
Without robust public backing, even the most scientifically sound and economically beneficial policies risk failure.
Therefore, comprehensive and reliable public opinion data is indispensable for crafting effective and enduring climate policies across various fields.
Building and supporting the CCPOD database is central to promoting scientific progress on these topics and aligns with NSF priorities outlined in the NSF Strategic Plan 2011-2016, particularly in transforming frontiers of knowledge by building research infrastructure and data access, facilitating international engagement in science, and emphasizing interdisciplinary research.


## Broader Impacts of the Proposed Work

The CCPOD will serve as a crucial research infrastructure for researchers, educators, students, policymakers, non-governmental organizations, and news agencies worldwide, fostering both within and cross-national work on climate change, polarization, and broader public opinion.
Dissemination of the resulting estimates will enhance our understanding of the relationship between public opinion and climate policies, ultimately contributing to more informed and effective climate change action.
We will achieve broad dissemination through conference presentations, a symposium, scholarly publications, and a web interface.
This aligns with NSF’s commitment to making knowledge accessible to policymakers, the public, and researchers.
Moreover, this project will promote teaching by providing CCPOD's web-based graphical interface with user-friendly functionality to facilitate its use for teaching and learning data analytics and by employing graduate research assistants, especially members of marginalized groups, who will develop valuable new skills in this important interdisciplinary field.