---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms2.tex
title: "Climate Change Attitudes"
#thanks: "Corresponding author: [xxxx@xxx.edu](mailto:xxx@xxx.edu).  Current version: `r format(Sys.time(), '%B %d, %Y')`."
author:
  - name: Yuehong Cassandra Tai
  #  affiliation:Penn State University
  - name: Xun Cao
  # affiliation:Penn State University
   - name: Fred Solt
  # affiliation:University of Iowa
anonymous: false
abstract: " "
keywords: " "
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
spacing: double
bibliography: \dummy{`r file.path(getwd(), list.files(getwd(), ".bib$", recursive = TRUE))`}
# csl: https://raw.githubusercontent.com/citation-style-language/styles/master/american-political-science-association.csl
biblio-style: apsr
citecolor: black
linkcolor: black
endnote: no
header-includes:
      
        - \usepackage{array}
      - \usepackage{caption}
      - \usepackage{graphicx}
      - \usepackage{siunitx}
      - \usepackage{colortbl}
      - \usepackage{multirow}
      - \usepackage{hhline}
      - \usepackage{calc}
      - \usepackage{tabularx}
      - \usepackage{threeparttable}
      - \usepackage{wrapfig}
      - \usepackage{fullpage}
      - \usepackage{lscape} #\usepackage{lscape} better for printing, page displayed vertically, content in landscape mode, \usepackage{pdflscape} better for screen, page displayed horizontally, content in landscape mode
      - \newcommand{\blandscape}{\begin{landscape}}
      - \newcommand{\elandscape}{\end{landscape}}
      - \usepackage{titlesec}
      - \titleformat*{\section}{\normalsize\bfseries}
      - \titleformat*{\subsection}{\normalsize\itshape}
      - \usepackage{titling} #use \maketitle repeatedly
---

```{r setup, include=FALSE}
options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE,
  dpi = 600,
  fig.width=7,
  fig.height = 2.5,
  plot = function(x, options)  {
    hook_plot_tex(x, options)
  }
)
remotes::install_github("fsolt/DCPO")
library(DCPOtools)
library(DCPO)
library(tidyverse)
library(countrycode)
library(patchwork)
library(rsdmx)
library(readxl)
library(stringr)
library(maps)

set.seed(313)
```


## Examining the Source Data on Climate Change(Broadly defined)

```{r cc_summary_stats}


surveys <-  read_csv(here::here("data-raw/climate_index_env.csv"),
                    col_types = "ccccccc") 

dcpo_input_raw_cc <- read_csv(here::here("data-raw/dcpo_input_raw_env.csv")) %>%
  select(-1)

with_min_coverage <- function(x, min_cov) {
  if (!is.na(min_cov)) {
    country <- year <- years <- spanned <- coverage <- NULL
    x <- x %>%
      group_by(country) %>%
      mutate(years = length(unique(year)),
             spanned = length(min(year):max(year)),
             coverage = years/spanned) %>%
      filter(coverage >= min_cov) %>%
      select(-years, -spanned, -coverage) %>%
      ungroup()
  }
  return(x)
}
with_max_gap <- function(x, max_gap, edges = TRUE) {
    if (!is.na(max_gap)) {
        country <- yr_obs <- NULL
        c_yrs <- x %>% 
            group_by(country, year) %>% 
            summarize(year = first(year)) %>% 
            mutate(lead_span = ifelse(!is.na(lead(year)),
                                      lead(year) - year - 1,
                                      50),
                   lag_span = ifelse(!is.na(lag(year)),
                                     year - lag(year) - 1,
                                     50),
                   min_span = pmin(lead_span, lag_span),
                   max_span = pmax(lead_span, lag_span),
                   drop = min_span > max_gap & max_span == 50)
        
        x <- x %>% 
          left_join(c_yrs,
                    by = c("country", "year")) %>% 
          filter(!drop) %>% 
          select(-contains("span")) %>% 
          select(-drop)
    }
    return(x)
}

process_dcpo_input_raw <- function(dcpo_input_raw_df) {
  dcpo_input_raw_df %>% 
    with_min_yrs(3) %>% 
    with_min_cy(5) %>% 
    with_min_yrs(3) %>% # double-check after dropping <5 cy
    filter(year >= 1972 & n > 0) %>% 
    group_by(country) %>% 
    mutate(cc_rank = n()) %>% 
    ungroup() %>% 
    arrange(-cc_rank)
}


dcpo_input_raw_cc <- process_dcpo_input_raw(dcpo_input_raw_cc)


n_surveys <- surveys %>%
  distinct(survey) %>% 
  nrow()  

n_items <- dcpo_input_raw_cc %>%
  distinct(item) %>% 
  nrow() 

n_countries <- dcpo_input_raw_cc %>%
  distinct(country) %>% 
  nrow()  

n_cy <- dcpo_input_raw_cc %>%
  distinct(country, year) %>% 
  nrow() %>% 
  scales::comma() 

n_years <- as.integer(summary(dcpo_input_raw_cc$year)[6]-summary(dcpo_input_raw_cc$year)[1]) 

spanned_cy <- dcpo_input_raw_cc %>% 
  group_by(country) %>% 
  summarize(years = max(year) - min(year) + 1) %>% 
  summarize(n = sum(years)) %>% 
  pull(n) %>% 
  scales::comma() 

total_cy <- {n_countries * n_years} %>% 
  scales::comma()  

year_range <- paste("from",
                    summary(dcpo_input_raw_cc$year)[1], 
                    "to",
                    summary(dcpo_input_raw_cc$year)[6]) 
n_cyi <- dcpo_input_raw_cc %>% 
  distinct(country, year, item) %>% 
  nrow() %>% 
  scales::comma() 
back_to_numeric <- function(string_number) {
  string_number %>% 
    str_replace(",", "") %>% 
    as.numeric()
}

```

```{r itemcountry, fig.cap="Countries and Years with the Most Observations in the Source Data \\label{item_country_plots}", fig.height=3.5, fig.pos='h', cache=FALSE}


countries_plot <- dcpo_input_raw_cc %>%
  mutate(country = if_else(stringr::str_detect(country, "United"),
                           stringr::str_replace(country, "((.).*) ((.).*)", "\\2.\\4."),
                           country)) %>% 
  distinct(country, year, item) %>% 
  count(country) %>%
  arrange(desc(n)) %>% 
  head(12) %>% 
  ggplot(aes(forcats::fct_reorder(country, n, .desc = TRUE), n)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x  = element_text(angle = 90, vjust = .45, hjust = .95, size = 7),
        axis.title.y = element_text(size = 9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  ylab("Year-Items\nObserved") +
  ggtitle("Countries")


cby_plot <- dcpo_input_raw_cc %>%
  mutate(country = if_else(stringr::str_detect(country, "United"),
                           stringr::str_replace(country, "((.).*) ((.).*)", "\\2.\\4."),
                           country),
         country = stringr::str_replace(country, "South", "S.")) %>% 
  distinct(country, year) %>%
  count(country) %>% 
  arrange(desc(n)) %>% 
  head(12) %>% 
  ggplot(aes(forcats::fct_reorder(country, n, .desc = TRUE), n)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x  = element_text(angle = 90, vjust = .45, hjust = .95),
        axis.title.y = element_text(size = 9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  ylab("Years\nObserved") +
  ggtitle("Countries")

ybc_plot <- dcpo_input_raw_cc %>%
  distinct(country, year) %>%
  count(year, name = "nn") %>%
  ggplot(aes(year, nn)) +
  geom_bar(stat = "identity") +
   scale_x_continuous(
    minor_breaks = seq(1989, 2023, by = 1),
    breaks = seq(1990, 2023, by = 2), limits = c(1989, 2023))  +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        # axis.text.x  = element_text(angle = 90, vjust = .45, hjust = .95),
        axis.text.x = element_text(size = 7),
        axis.title.y = element_text(size = 9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  xlab("Year") +
  ylab("Countries\nObserved") +
  ggtitle("Year")

world_map <- map_data("world") %>% 
  filter(!long > 180)

cby_map <- world_map %>% 
  distinct(region) %>% 
  mutate(country = countrycode::countrycode(region,
                                            "country.name",
                                            "country.name")) %>% 
  filter(!region=="Antarctica") %>% 
  left_join(dcpo_input_raw_cc %>% 
              count(country, year) %>% 
              count(country, name = "Years"),
            by = "country") %>% 
  mutate(Years = ifelse(is.na(Years), 0, Years)) %>% 
  ggplot(aes(fill = Years, map_id = region)) +
  geom_map(map = world_map,
           color = "white",
           size = 0.06) +
  coord_map(projection = "mollweide", 
            ylim=c(-80, 90),
            xlim=c(-170, 170)) +
  theme_void() +
  scale_fill_distiller(na.value = "gray90", 
                       palette = "Blues",
                       direction = 1) +
  ggtitle("Years Observed by Country") +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = c(.05,.1),
        legend.justification = c(0,0), 
        legend.direction = "vertical") +
  scale_y_continuous(expand=c(0,0)) +
scale_x_continuous(expand=c(0,0))
cby_map + (countries_plot/ ybc_plot) + plot_layout(widths = c(4, 1))
```

```{r cc_item_and_country_plots, fig.height = 3.5, fig.cap = "Countries and Years with the Most Observations in the Source Data of Climate Change \\label{cc_item_country_plots}"}

items_plot <- dcpo_input_raw_cc %>%
  distinct(country, year, item) %>%
  count(item) %>%
  arrange(desc(n)) %>% 
  head(12) %>% 
  ggplot(aes(forcats::fct_reorder(item, n, .desc = TRUE), n)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x  = element_text(angle = 90, vjust = .45, hjust = .95),
        axis.title.y = element_text(size = 9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  ylab("Country-Years\nObserved") +
  ggtitle("Items")

## gen_clicon_2  climate_chg_4 gen_clicon_4

t <- dcpo_input_raw_cc %>%
  distinct(country, item, year) %>%
  group_by(country, item) %>%
  summarise(n = n())

t <- dcpo_input_raw_cc %>%
  distinct(country, item, year) %>%
  group_by(year, item) %>%
  summarise(n = n())

most_common_item <- dcpo_input_raw_cc %>% 
  count(item) %>% 
  arrange(-n) %>% 
  slice_head() %>% 
  pull(item) #gen_clicon_10

un_cy <- dcpo_input_raw_cc %>% filter(item == "gen_clicon_2") %>% distinct(country, year) %>% nrow() #578

un_surveys <- dcpo_input_raw_cc %>% filter(item == "gen_clicon_2") %>% distinct(survey) %>% pull(survey) #39

#sum(stringr::str_detect(un_surveys, ",")) #30 has multiple surveys

unique_survey <- length(unique(unlist(strsplit(un_surveys, ", ", fixed = TRUE)))) #42

#countries_plot
   #Germany spain france

most_common_item_cy <- dcpo_input_raw_cc %>% 
  filter(item == most_common_item) %>%
  distinct(country, year) %>%
  nrow()  #201

most_common_item_surveys <- dcpo_input_raw_cc %>%
  filter(item == most_common_item) %>%
  distinct(survey) %>%
  pull(survey) %>% 
  str_split(", ") %>% 
  unlist() %>% 
  unique() %>% 
  sort()

top_country_cyi <- dcpo_input_raw_cc %>% 
  distinct(country, year, item) %>%
  count(country) %>%
  arrange(-n) %>% 
  slice_head() %>%
 pull(country) 

top_country_cyi_obs <- dcpo_input_raw_cc %>%
  filter(country == top_country_cyi) %>%
  distinct(country, year, item) %>%
  nrow()  

others_cc <- dcpo_input_raw_cc %>%
  distinct(country, year, item) %>%
  count(country) %>%
  arrange(desc(n)) %>%
  slice(2:5) %>%
  pull(country) %>% 
  paste(collapse = ", ") %>% 
  str_replace(", (\\w+)$", ", and \\1") # "Spain, France, Italy, and Netherlands""

countries_cp <- dcpo_input_raw_cc %>%
  mutate(country = if_else(stringr::str_detect(country, "United"),
                           stringr::str_replace(country, "((.).*) ((.).*)", "\\2.\\4."),
                           country),
         country = stringr::str_replace(country, "South", "S.")) %>% 
  distinct(country, year, item) %>%
  count(country) %>% 
  arrange(desc(n)) %>% 
  head(20) %>% 
  pull(country)

countries_cbyp <- dcpo_input_raw_cc %>%
  mutate(country = if_else(stringr::str_detect(country, "United"),
                           stringr::str_replace(country, "((.).*) ((.).*)", "\\2.\\4."),
                           country),
         country = stringr::str_replace(country, "South", "S.")) %>% 
  distinct(country, year) %>%
  count(country) %>% 
  arrange(desc(n)) %>% 
  head(20) %>% 
  pull(country)

adding_cc <- setdiff(countries_cbyp, countries_cp) %>% 
  paste(collapse = ", ") %>% 
  str_replace(", (\\w*)$", ", and \\1")  #""

dropping_cc <- setdiff(countries_cp, countries_cbyp) %>% 
  paste(collapse = ", ") %>% 
  str_replace(", (\\w*)$", ", and \\1")  ##""

y_cc_peak_year <- dcpo_input_raw_cc %>%
  distinct(country, year) %>%
  count(year, name = "nn") %>% 
  filter(nn == max(nn)) %>% 
  pull(year) #2010

y_cc_peak_nn <- dcpo_input_raw_cc %>%
  distinct(country, year) %>%
  count(year, name = "nn") %>% 
  filter(nn == max(nn)) %>% 
  pull(nn) #84 countries

data_cc_poorest <- dcpo_input_raw_cc %>%
  distinct(country, year, item) %>%
  count(country) %>%
  arrange(n) %>%
  filter(n == min(n)) %>%
  pull(country) %>% 
  paste(collapse = ", ") %>% 
  str_replace(", (\\w+)$", ", and \\1")  #Algeria, and Libya

wordify_numeral <- function(x) setNames(c("one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", " seventeen", "eighteen", "nineteen"), 1:19)[x]



n_cc_data_poorest <- {data_cc_poorest %>%
    str_split(",") %>% 
    first()} %>% 
  length() %>% 
  wordify_numeral()

(countries_plot + cby_plot) / (ybc_plot)

```


```{r inputdata}
dcpo_input_raw_env <- read_csv(here::here("data-raw/dcpo_input_raw_env.csv")) %>%
  select(-1) %>%
  filter(!str_detect(item, "_300|_100"))

dcpo_input_raw <- process_dcpo_input_raw(dcpo_input_raw_env)

dcpo_input <- DCPOtools::format_dcpo(dcpo_input_raw,
                                     scale_q = "gen_clicon_4",
                                     scale_cp = 3)
save(dcpo_input, file = here::here("data/env", "dcpo_input.rda"))

```


```{r}
iter <- 2000
dcpo <- cmdstan_model("R/dcpo.stan")

dcpo_output <- dcpo$sample(
  data = dcpo_input[1:13], 
  max_treedepth = 14,
  adapt_delta = 0.99,
  step_size = 0.005,
  seed = 324, 
  chains = 4, 
  parallel_chains = 4,
  iter_warmup = iter/2,
  iter_sampling = iter/2,
  refresh = iter/50
)

results_path <- here::here(file.path("data/env", 
                                     iter, 
                                     {str_replace_all(Sys.time(), "[- :]", "") %>%
                                         str_replace("\\d{2}$", "")}))
dir.create(results_path, 
           showWarnings = FALSE, 
           recursive = TRUE)
dcpo_output$save_data_file(dir = results_path,
                           random = FALSE)
dcpo_output$save_output_files(dir = results_path,
                              random = FALSE)

if (!exists("results_path")) {
  latest <- "20240529225002"
  results_path <- here::here("data/env", "2000", latest)
  
  # Define OSF_PAT in .Renviron: https://docs.ropensci.org/osfr/articles/auth
  if (!file.exists(file.path(results_path, paste0("dcpo-", latest, "-1.csv")))) {
    dir.create(results_path, showWarnings = FALSE, recursive = TRUE)
    osf_retrieve_node("") %>% 
      osf_ls_files(pattern = "csv$") %>% 
      osf_download(path = here::here("data", "2000"))
  }
  
  if(!file.exists(here::here("data/env", "dcpo_output.rds"))) {
    dcpo_output <- as_cmdstan_fit(paste0(results_path, "/",
                                             list.files(results_path, pattern = "csv$")))
    
    dcpo_output$save_object(here::here("data/env", "dcpo_output.rds"))
  }
}

dcpo_output <- readRDS(here::here("data/env", "dcpo_output.rds"))



load(file = here::here("data/env", "dcpo_input.rda"))
theta_summary <- DCPOtools::summarize_dcpo_results(dcpo_input,
                                                   dcpo_output,
                                                   "theta")
mean(theta_summary$rhat) #1.000819
min(theta_summary$ess_bulk) #634.4337
min(theta_summary$ess_tail) #1323.762

res_cy <- nrow(theta_summary) %>% 
  scales::comma()
res_c <- theta_summary %>% 
  pull(country) %>% 
  unique() %>% 
  length()
save(theta_summary, file = here::here("data/env","theta_summary.rda"))

dcpo_output$summary(variables = c("theta[5,12]", "theta[19,25]", "theta[25,38]","theta[30,80]"))

bayesplot::mcmc_trace(dcpo_output$draws("theta[5,22]"))
bayesplot::mcmc_trace(dcpo_output$draws("theta[19,58]"))
bayesplot::mcmc_trace(dcpo_output$draws("theta[25,88]"))
bayesplot::mcmc_trace(dcpo_output$draws("theta[33,113]"))

bayesplot::mcmc_acf(dcpo_output$draws("theta"), pars = "theta[20,75]", lags = 10)


theta_results <- extract_dcpo_results(dcpo_input,
                                      dcpo_output,
                                      par = "theta")

save(theta_results, file = here::here("data/env","theta_results.rda"))

```

```{r}
n_panes <- 2
axis_text_size <- 10
p1_data <- theta_summary %>%
  filter(!country %in% c("Taiwan","German Democratic Republic", "North Ireland")) %>%
  group_by(country) %>%
  top_n(1, year) %>%
  ungroup() %>%
  arrange(mean) %>%
  transmute(country_year = paste0(country, " (", year, ")") %>% 
              str_replace("’", "'"),
            estimate = mean,
            conf.high = q90,
            conf.low = q10,
            pane = n_panes - (ntile(mean, n_panes) - 1),
            ranked = as.factor(ceiling(row_number())))
top5 <- p1_data %>% 
  arrange(desc(ranked)) %>% 
  slice(1:5) %>% 
  pull(country_year) %>% 
  str_replace(" \\(.*", "") %>% 
  knitr::combine_words()
bottom5 <- p1_data %>% 
  arrange(ranked) %>% 
  slice(1:5) %>% 
  pull(country_year) %>% 
  str_replace(" \\(.*", "") %>% 
  knitr::combine_words()



p_theta <- ggplot(p1_data,
                  aes(x = estimate, y = ranked)) +
  geom_segment(aes(x = conf.low, xend = conf.high,
                   y = ranked, yend = ranked),
               na.rm = TRUE,
               alpha = .4) +
  geom_point(fill = "black", shape = 21, size = .5, na.rm = TRUE) +
  theme_bw() + theme(legend.position="none",
                     axis.text.x  = element_text(size = axis_text_size,
                                                 angle = 90,
                                                 vjust = .45,
                                                 hjust = .95),
                     axis.text.y  = element_text(size = axis_text_size),
                     axis.title = element_blank(),
                     strip.background = element_blank(), 
                     strip.text = element_blank(),
                     panel.grid.major = element_line(linewidth = .3),
                     panel.grid.minor = element_line(linewidth = .15)) +
  scale_y_discrete(breaks = p1_data$ranked, labels=p1_data$country_year) +
  coord_cartesian(xlim=c(0, 1)) +
  facet_wrap(vars(pane), scales = "free", nrow = 1)
p_theta +
  patchwork::plot_annotation(caption = "Note: Gray whiskers represent 80% credible intervals.")

```

```{r itemsummary}
alpha_results <- summarize_dcpo_results(dcpo_input,
                                        dcpo_output = dcpo_output,
                                        pars = "alpha") %>% 
  transmute(item = question,
            dispersion = mean)

beta_results <- summarize_dcpo_results(dcpo_input,
                                       dcpo_output,
                                       "beta") %>% 
  group_by(question) %>% 
  summarize(difficulties0 = paste0(sprintf("%.2f", round(mean, 2)),
                                   collapse = ", ")) %>% 
  mutate(item = question,
        cp = as.numeric(str_extract(item, "\\d+")) - 1,
        term = str_glue("(( ?-?[0-9].[0-9][0-9]?,?){{{cp}}})"),
         difficulties = str_extract(difficulties0, 
                                    term) %>%
           str_replace(",$", "") %>% 
           str_trim()) %>% 
  transmute(item, difficulties)

items_summary <- alpha_results  %>%
  left_join(beta_results)

write.csv(items_summary, here::here("output","items_summary.csv"))

 items_summary <- dcpo_input_raw %>%
   dplyr::select(country, year, item, survey) %>%
   distinct() %>%
   separate(survey, c("surv1", "surv2", "surv3"), sep=", ", fill = "left") %>%
   pivot_longer(cols = starts_with("surv"), values_to = "survey") %>%
   filter(!is.na(survey)) %>% 
   group_by(item) %>% 
   mutate(survey = str_extract(survey, "^[a-z]*"),
          all_surveys = paste0(unique(survey), collapse = ", ")) %>% 
   ungroup() %>% 
   distinct(country, year, item, .keep_all = TRUE) %>% 
   group_by(item) %>% 
   mutate(n_cy = n()) %>% 
   ungroup() %>%
   distinct(item, n_cy, all_surveys) %>% 
   left_join(surveys %>%
               select(item, question_text, response_categories) %>%
               distinct(item, .keep_all = TRUE),
             by = "item") %>% 
   left_join(alpha_results, by = "item") %>% 
   left_join(beta_results, by = "item") %>% 
   arrange(-n_cy)

```



```{r internal_validation}

internal_dat <- dcpo_input$data %>% 
  filter(item == "gen_clicon_4 3 or higher") %>% 
  mutate(prop = y_r/n_r,
         se = sqrt((prop*(1-prop))/n),
         prop_90 = prop + qnorm(.9)*se,
         prop_10 = prop - qnorm(.9)*se) %>% 
  left_join(theta_summary %>% select(-kk, -tt), by = c("country", "year"))  #gen_clicon_4 3 or higher   gen_evncon_2 2 or higher


validation_cor <- theta_results %>%
  dplyr::inner_join(internal_dat %>%
               select(country, year, prop, se),
             by = c("country", "year"), multiple = "all")  %>% 
  rowwise() %>% 
  mutate(sim = rnorm(1, mean = prop, sd = se)) %>% 
  ungroup() %>% 
  select(theta, sim, draw) %>% 
  nest(data = c(theta, sim))    

cor <- map(validation_cor$data, function(x) with(x, cor(theta, sim))) %>% 
  unlist() %>% 
  mean() %>% 
  round(2) %>% 
  paste0("R = ", .)   #0.56


internal_label <- tibble(mean = .48, prop = .99, label = cor)
internal_plot <- internal_dat %>% 
  ggplot(aes(x = mean,
             y = prop * 100)) +
  geom_segment(aes(x = q10, xend = q90,
                   y = prop * 100, yend = prop * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_segment(aes(x = mean, xend = mean,
                   y = prop_90 * 100, yend = prop_10 * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_smooth(method = 'lm', se = FALSE) +
  theme_bw() +
  theme(legend.position="none",
        axis.text  = element_text(size=8),
        axis.title = element_text(size=9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  coord_cartesian(ylim=c(0,100)) +
  scale_x_continuous(breaks=seq(.1, .9, 0.2)) +
  labs(x = "Climate Change Attitudes", 
       y = '% Agreeing That \n"Climate Change is a threat"') + 
  ggtitle("All Country-Years") +
  geom_label(data = internal_label, aes(label = label), size = 3)



####sup_govation_ 2  climate_eco_4  climate_chg_2  ind_change_4

internal_eco_dat <- dcpo_input$data %>% 
  filter(item == "climate_eco_4 3 or higher") %>% 
  mutate(prop = y_r/n_r,
         se = sqrt((prop*(1-prop))/n),
         prop_90 = prop + qnorm(.9)*se,
         prop_10 = prop - qnorm(.9)*se) %>% 
  left_join(theta_summary %>% select(-kk, -tt), by = c("country", "year"))  #gen_clicon_4 3 or higher   #sup_govation_ 2  


validation_eco_cor <- theta_results %>%
  dplyr::inner_join(internal_eco_dat %>%
                      select(country, year, prop, se),
                    by = c("country", "year"), multiple = "all")  %>% 
  rowwise() %>% 
  mutate(sim = rnorm(1, mean = prop, sd = se)) %>% 
  ungroup() %>% 
  select(theta, sim, draw) %>% 
  nest(data = c(theta, sim))    

eco_cor <- map(validation_eco_cor$data, function(x) with(x, cor(theta, sim))) %>% 
  unlist() %>% 
  mean() %>% 
  round(2) %>% 
  paste0("R = ", .)   #0.56


internal_eco_label <- tibble(mean = .48, prop = .99, label = eco_cor)
internal_eco_plot <- internal_eco_dat %>% 
  ggplot(aes(x = mean,
             y = prop * 100)) +
  geom_segment(aes(x = q10, xend = q90,
                   y = prop * 100, yend = prop * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_segment(aes(x = mean, xend = mean,
                   y = prop_90 * 100, yend = prop_10 * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_smooth(method = 'lm', se = FALSE) +
  theme_bw() +
  theme(legend.position="none",
        axis.text  = element_text(size=8),
        axis.title = element_text(size=9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  coord_cartesian(ylim=c(0,100)) +
  scale_x_continuous(breaks=seq(.1, .9, 0.2)) +
  labs(x = "Climate Change Attitudes", 
       y = '% Agreeing That \n"Climate Change precedes economic growth"') + 
  ggtitle("All Country-Years") +
  geom_label(data = internal_eco_label, aes(label = label), size = 3)



#######sup_govation_ 2  0.66  climate_eco_4  climate_chg_2  ind_change_4

internal_gov_dat <- dcpo_input$data %>% 
  filter(item == "sup_govaction_2 2 or higher") %>% 
  mutate(prop = y_r/n_r,
         se = sqrt((prop*(1-prop))/n),
         prop_90 = prop + qnorm(.9)*se,
         prop_10 = prop - qnorm(.9)*se) %>% 
  left_join(theta_summary %>% select(-kk, -tt), by = c("country", "year"))  #


validation_gov_cor <- theta_results %>%
  dplyr::inner_join(internal_gov_dat %>%
                      select(country, year, prop, se),
                    by = c("country", "year"), multiple = "all")  %>% 
  rowwise() %>% 
  mutate(sim = rnorm(1, mean = prop, sd = se)) %>% 
  ungroup() %>% 
  select(theta, sim, draw) %>% 
  nest(data = c(theta, sim))    

gov_cor <- map(validation_gov_cor$data, function(x) with(x, cor(theta, sim))) %>% 
  unlist() %>% 
  mean() %>% 
  round(2) %>% 
  paste0("R = ", .)   #0.66


internal_gov_label <- tibble(mean = .48, prop = .99, label = gov_cor)
internal_gov_plot <- internal_gov_dat %>% 
  ggplot(aes(x = mean,
             y = prop * 100)) +
  geom_segment(aes(x = q10, xend = q90,
                   y = prop * 100, yend = prop * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_segment(aes(x = mean, xend = mean,
                   y = prop_90 * 100, yend = prop_10 * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_smooth(method = 'lm', se = FALSE) +
  theme_bw() +
  theme(legend.position="none",
        axis.text  = element_text(size=8),
        axis.title = element_text(size=9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  coord_cartesian(ylim=c(0,100)) +
  scale_x_continuous(breaks=seq(.1, .9, 0.2)) +
  labs(x = "Climate Change Attitudes", 
       y = '% Support Policy"') + 
  ggtitle("All Country-Years") +
  geom_label(data = internal_gov_label, aes(label = label), size = 3)



internal_klg_dat <- dcpo_input$data %>% 
  filter(item == "climate_chg_2 2 or higher") %>% 
  mutate(prop = y_r/n_r,
         se = sqrt((prop*(1-prop))/n),
         prop_90 = prop + qnorm(.9)*se,
         prop_10 = prop - qnorm(.9)*se) %>% 
  left_join(theta_summary %>% select(-kk, -tt), by = c("country", "year"))  


validation_klg_cor <- theta_results %>%
  dplyr::inner_join(internal_klg_dat %>%
                      select(country, year, prop, se),
                    by = c("country", "year"), multiple = "all")  %>% 
  rowwise() %>% 
  mutate(sim = rnorm(1, mean = prop, sd = se)) %>% 
  ungroup() %>% 
  select(theta, sim, draw) %>% 
  nest(data = c(theta, sim))    

klg_cor <- map(validation_klg_cor$data, function(x) with(x, cor(theta, sim))) %>% 
  unlist() %>% 
  mean() %>% 
  round(2) %>% 
  paste0("R = ", .)   #0.66


internal_klg_label <- tibble(mean = .48, prop = .99, label = klg_cor)
internal_klg_plot <- internal_klg_dat %>% 
  ggplot(aes(x = mean,
             y = prop * 100)) +
  geom_segment(aes(x = q10, xend = q90,
                   y = prop * 100, yend = prop * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_segment(aes(x = mean, xend = mean,
                   y = prop_90 * 100, yend = prop_10 * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_smooth(method = 'lm', se = FALSE) +
  theme_bw() +
  theme(legend.position="none",
        axis.text  = element_text(size=8),
        axis.title = element_text(size=9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  coord_cartesian(ylim=c(0,100)) +
  scale_x_continuous(breaks=seq(.1, .9, 0.2)) +
  labs(x = "Climate Change Attitudes", 
       y = '% Climate Change Knowledge"') + 
  ggtitle("All Country-Years") +
  geom_label(data = internal_klg_label, aes(label = label), size = 3)



internal_ind_dat <- dcpo_input$data %>% 
  filter(item == "gen_indchge_2 2 or higher") %>% 
  mutate(prop = y_r/n_r,
         se = sqrt((prop*(1-prop))/n),
         prop_90 = prop + qnorm(.9)*se,
         prop_10 = prop - qnorm(.9)*se) %>% 
  left_join(theta_summary %>% select(-kk, -tt), by = c("country", "year"))  


validation_ind_cor <- theta_results %>%
  dplyr::inner_join(internal_ind_dat %>%
                      select(country, year, prop, se),
                    by = c("country", "year"), multiple = "all")  %>% 
  rowwise() %>% 
  mutate(sim = rnorm(1, mean = prop, sd = se)) %>% 
  ungroup() %>% 
  select(theta, sim, draw) %>% 
  nest(data = c(theta, sim))    

ind_cor <- map(validation_ind_cor$data, function(x) with(x, cor(theta, sim))) %>% 
  unlist() %>% 
  mean() %>% 
  round(2) %>% 
  paste0("R = ", .)   #0.41


internal_ind_label <- tibble(mean = .48, prop = .99, label = ind_cor)
internal_ind_plot <- internal_ind_dat %>% 
  ggplot(aes(x = mean,
             y = prop * 100)) +
  geom_segment(aes(x = q10, xend = q90,
                   y = prop * 100, yend = prop * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_segment(aes(x = mean, xend = mean,
                   y = prop_90 * 100, yend = prop_10 * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_smooth(method = 'lm', se = FALSE) +
  theme_bw() +
  theme(legend.position="none",
        axis.text  = element_text(size=8),
        axis.title = element_text(size=9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  coord_cartesian(ylim=c(0,100)) +
  scale_x_continuous(breaks=seq(.1, .9, 0.2)) +
  labs(x = "Climate Change Attitudes", 
       y = '% Individual Behavior Change') + 
  ggtitle("All Country-Years") +
  geom_label(data = internal_ind_label, aes(label = label), size = 3)


dcpo_input$data %>%
  distinct(year,country) %>%
  group_by(year) %>%
  summarise(n = n()) %>%
  arrange(-n)  #2010, 2017


## Cross-sectional
internal_policysupport <- dcpo_input$data %>% 
  filter(item == "sup_govaction_2 2 or higher" & year == 2015) %>% 
  mutate(iso2c = countrycode::countrycode(country,
                                          origin = "country.name",
                                          destination = "iso2c"),   
         prop = y_r/n_r,
         se = sqrt((prop*(1-prop))/n),
         prop_90 = prop + qnorm(.9)*se,
         prop_10 = prop - qnorm(.9)*se) %>% 
  left_join(theta_summary %>% select(-kk, -tt), by = c("country", "year"))


validation_cor_cs <- theta_results %>%
  dplyr::inner_join(internal_policysupport %>%
                      select(country, year, prop, se),
                    by = c("country", "year"), multiple = "all")  %>% 
  rowwise() %>% 
  mutate(sim = rnorm(1, mean = prop, sd = se)) %>% 
  ungroup() %>% 
  select(theta, sim, draw) %>% 
  nest(data = c(theta, sim))    

internal_cs_cor <- map(validation_cor_cs$data, function(x) with(x, cor(theta, sim))) %>% 
  unlist() %>% 
  mean() %>% 
  round(2) %>% 
  paste0("R = ", .)  #


internal_cs_label <- tibble(mean = .45, prop = .73, label = internal_cs_cor)
internal_cs_plot <- internal_policysupport %>% 
  ggplot(aes(x = mean,
             y = prop * 100)) +
  geom_segment(aes(x = q10, xend = q90,
                   y = prop * 100, yend = prop * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_segment(aes(x = mean, xend = mean,
                   y = prop_90 * 100, yend = prop_10 * 100),
               na.rm = TRUE,
               alpha = .2) +
  geom_text(aes(label = iso2c), size = 2) +
  geom_smooth(method = 'lm', se = FALSE) +
  theme_bw() +
  theme(legend.position="none",
        axis.text  = element_text(size=8),
        axis.title = element_text(size=9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  labs(x = "Climate Change Attitude", 
       y = '% Support Movements of Government\n in Fighting Cliamte Change') + 
  ggtitle("Pew, 2015") +
  geom_label(data = internal_cs_label, aes(label = label), size = 3)



#### Longitudinal

internal_ts_dat <- dcpo_input_raw1 %>% 
  filter(survey == "usgss" & item == "trust3") %>%  
  mutate(title = "United States",
         neg = FALSE)

internal_ts_plot <- validation_plot(internal_ts_dat,
                                    lab_x = 1989,
                                    lab_y = .95) +
  theme_bw() +
  theme(legend.position="none",
        axis.text  = element_text(size=8),
        axis.title = element_text(size=9),
        plot.title = element_text(hjust = 0.5, size = 9),
        strip.background = element_blank()) +
  coord_cartesian(ylim = c(0,1)) +
  labs(x = "Year",
       y = "Score") +
  annotate("text", x = 2005, y = .8, size = 2,
           label = 'U.S. GSS') + #confidence in executive branch
  annotate("text", x = 2008, y = .32, size = 2,
           label = "TCS Score")

internal_tscs_plot + internal_cs_plot + internal_ts_plot  +
  patchwork::plot_annotation(caption = "Note: Gray whiskers and shading represent 80% credible intervals.")


t_ge <- dcpo_input$data  %>% filter(country == "Germany") %>% 
 distinct(item,survey,year)  #%>% 
  group_by(item, survey) %>% 
  summarise(n = n())
  
t_us <- dcpo_input$data  %>% filter(country == "United States") %>% 
    distinct(item,survey,year)  #%>% 
  group_by(item, survey) %>% 
    summarise(n = n())

####The who part need to double check, something wrong here. country score is so similar among all contries. 
internal_us <- dcpo_input$data %>% 
  filter(item == "gen_clicon_4 3 or higher") %>% 
  mutate(prop = y_r/n_r,
         se = sqrt((prop*(1-prop))/n),
         prop_90 = prop + qnorm(.9)*se,
         prop_10 = prop - qnorm(.9)*se) %>% 
  right_join(theta_summary %>% 
               select(-kk, -tt) %>%
               filter(country == "United States" & year > 2005),
             by = c("country", "year")) #gen_clicon_4 3 or higher   sup_govaction_4 3 or higher 0.66   gen_clicon_5 3 or higher   gen_clicon_3 3 or higher --- super low



validation_cor_time <- theta_results %>%
  dplyr::inner_join(internal_us %>%
                      select(country, year, prop, se),
                    by = c("country", "year"), multiple = "all")  %>% 
  rowwise() %>% 
  mutate(sim = rnorm(1, mean = prop, sd = se)) %>% 
  ungroup() %>% 
  select(theta, sim, draw) %>% 
  filter(!(is.na(theta)|is.na(sim))) %>% 
  nest(data = c(theta, sim))    


internal_us_cor <- map(validation_cor_time$data, function(x) with(x, cor(theta, sim)))  %>% 
  unlist()  %>% 
  mean() %>% 
  round(2) %>% 
  paste0("R = ", .)  #

internal_us_label <- tibble(year = 2010, mean = .57, label = internal_us_cor)

internal_us_plot <- internal_us %>% 
  ggplot(aes(x = year,
             y = mean)) +
  geom_line() +
  geom_ribbon(aes(ymin = q10,
                  ymax = q90,
                  linetype = NA),
              alpha = .2) +
  geom_point(aes(y = prop),
             fill = "black",
             shape = 21,
             size = .5,
             na.rm = TRUE) +
  geom_path(aes(y = prop),
            linetype = 3,
            na.rm = TRUE,
            alpha = .7) +
  geom_segment(aes(x = year, xend = year,
                   y = prop_90, yend = prop_10),
               na.rm = TRUE,
               alpha = .2) +
  annotate("text", x = 2010, y = .7, size = 2,
           label = 'US') +
  annotate("text", x = 2012, y = .50, size = 2,
           label = "Climate Change Attitude") +
  labs(x = "Year", 
       y = "Score") +
  theme_bw() +
  theme(legend.position="none",
        axis.text  = element_text(size=8),
        axis.title = element_text(size=9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  ggtitle("United States") +
  geom_label(data = internal_us_label, aes(label = label), size = 3)

internal_us_plot

#####gen_evncon_2

internal_ge <- dcpo_input$data %>% 
  filter(item == "gen_clicon_2 2 or higher") %>% 
  mutate(prop = y_r/n_r,
         se = sqrt((prop*(1-prop))/n),
         prop_90 = prop + qnorm(.9)*se,
         prop_10 = prop - qnorm(.9)*se) %>% 
  right_join(theta_summary %>% 
               select(-kk, -tt) %>%
               filter(country == "Germany"),
             by = c("country", "year")) #gen_clicon_2 2 or higher


validation_cor_getime <- theta_results %>%
  dplyr::inner_join(internal_ge %>%
                      select(country, year, prop, se),
                    by = c("country", "year"), multiple = "all")  %>% 
  rowwise() %>% 
  mutate(sim = rnorm(1, mean = prop, sd = se)) %>% 
  ungroup() %>% 
  select(theta, sim, draw) %>% 
  filter(!(is.na(theta)|is.na(sim))) %>% 
  nest(data = c(theta, sim))    


internal_ge_cor <- map(validation_cor_getime$data, function(x) with(x, cor(theta, sim)))  %>% 
  unlist()  %>% 
  mean() %>% 
  round(2) %>% 
  paste0("R = ", .)  #

internal_ge_label <- tibble(year = 1991, mean = .57, label = internal_ge_cor)

internal_ge_plot <- internal_ge %>% 
  ggplot(aes(x = year,
             y = mean)) +
  geom_line() +
  geom_ribbon(aes(ymin = q10,
                  ymax = q90,
                  linetype = NA),
              alpha = .2) +
  geom_point(aes(y = prop),
             fill = "black",
             shape = 21,
             size = .5,
             na.rm = TRUE) +
  geom_path(aes(y = prop),
            linetype = 3,
            na.rm = TRUE,
            alpha = .7) +
  geom_segment(aes(x = year, xend = year,
                   y = prop_90, yend = prop_10),
               na.rm = TRUE,
               alpha = .2) +
  annotate("text", x = 2015, y = .2, size = 2,
           label = 'Germany Support Government') +
  annotate("text", x = 2012, y = .50, size = 2,
           label = "Climate Change Attitude") +
  labs(x = "Year", 
       y = "Score") +
  theme_bw() +
  theme(legend.position="none",
        axis.text  = element_text(size=8),
        axis.title = element_text(size=9),
        plot.title = element_text(hjust = 0.5, size = 11)) +
  ggtitle("Germany") +
  geom_label(data = internal_ge_label, aes(label = label), size = 3)

internal_ge_plot

(internal_plot +  internal_cs_plot )/(internal_us_plot + internal_ge_plot)


(internal_eco_plot +  internal_gov_plot)  / (internal_klg_plot  + internal_ind_plot)


```

